// Code generated by go-bindata.
// sources:
// _boilerplate/functions/hello/index.js
// _boilerplate/infrastructure/.gitignore
// _boilerplate/infrastructure/modules/iam/iam.tf
// _boilerplate/infrastructure/modules/iam/outputs.tf
// _boilerplate/infrastructure/modules/iam/variables.tf
// _boilerplate/infrastructure/prod/main.tf
// _boilerplate/infrastructure/prod/terraform.tfvars
// _boilerplate/infrastructure/stage/main.tf
// _boilerplate/infrastructure/stage/terraform.tfvars
// DO NOT EDIT!

package boilerplate

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _functionsHelloIndexJs = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x54\xcc\x41\x0a\x83\x30\x10\x46\xe1\x7d\x4e\x31\x9b\x12\x03\xe2\x01\x84\x9e\xa2\x27\x90\xc9\x5f\xb5\x0c\x33\x92\x8c\x6d\x40\xbc\x7b\x71\x53\xe8\xfa\x3d\xbe\xc0\xa6\xd5\x04\x83\xd8\xdc\xc5\x87\x4f\xc5\x57\x9d\xe9\xb9\x2b\xfb\x6a\x1a\x53\x40\xdb\xac\x78\x1d\x96\x49\xb3\x80\xee\xbf\xd6\xa1\x27\xf6\x96\xe8\x08\x44\x7f\xcc\x56\x8c\x51\xeb\x05\xe1\x0d\xf5\x91\x6e\xaf\xd8\x13\xd2\x35\x7a\x1b\xea\xce\x0c\xe4\xee\xa0\x05\x22\x36\x52\xfc\x58\x91\x1c\xe9\x4c\xe1\x0c\xdf\x00\x00\x00\xff\xff\x39\x99\x33\xdc\x93\x00\x00\x00")

func functionsHelloIndexJsBytes() ([]byte, error) {
	return bindataRead(
		_functionsHelloIndexJs,
		"functions/hello/index.js",
	)
}

func functionsHelloIndexJs() (*asset, error) {
	bytes, err := functionsHelloIndexJsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "functions/hello/index.js", size: 147, mode: os.FileMode(420), modTime: time.Unix(1455672076, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _infrastructureGitignore = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xd2\x2b\x49\x2d\x2a\x4a\x4c\xcb\x2f\xca\xe5\x02\x04\x00\x00\xff\xff\x56\x5a\xd5\x12\x0b\x00\x00\x00")

func infrastructureGitignoreBytes() ([]byte, error) {
	return bindataRead(
		_infrastructureGitignore,
		"infrastructure/.gitignore",
	)
}

func infrastructureGitignore() (*asset, error) {
	bytes, err := infrastructureGitignoreBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "infrastructure/.gitignore", size: 11, mode: os.FileMode(420), modTime: time.Unix(1455671208, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _infrastructureModulesIamIamTf = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xac\x91\xbd\x6e\xf2\x30\x14\x86\x77\x5f\x85\x65\x7d\x13\x82\x08\x58\x3e\x29\xa2\x43\x06\xba\xb6\xa2\x52\x17\x84\xa2\x53\xe7\xa4\xb5\xe4\x1f\x64\x3b\x8d\x5a\x94\x7b\xaf\x8f\x09\xf4\xbf\x5d\xca\xc0\xe0\xf7\x39\xc7\x7e\x9f\x30\x8f\xc1\x75\x5e\x22\x17\xd0\x87\x5a\x81\xa9\xbd\xd3\x28\xb8\xd0\x60\xee\x1a\xa8\xdb\xce\xca\xa8\x9c\x15\xfc\xc0\x38\xb7\x60\x90\x5f\x7c\x0e\x53\x04\x21\x74\x06\xf3\x74\xbd\x77\x5a\xc9\xa7\x04\xae\x56\xeb\xab\x4b\x46\x93\xe2\x16\x7d\x20\xb4\xe4\x62\x39\x5f\x2c\x67\x8b\xf9\x6c\xf1\x5f\x4c\x29\xba\x89\x10\xd1\xa0\x8d\x29\xdc\xa6\x03\x9e\xef\xa2\x9f\x58\xb7\x2d\x4a\x3a\x17\x95\xd6\xae\xcf\x7c\x0e\xae\xbd\xb2\x52\xed\x41\xa7\xec\x44\xd3\x2a\xf4\x8f\x4a\x22\x0d\x1c\xdf\x58\x80\x81\x67\x67\x53\xb9\x42\x3a\x23\x46\x72\x38\xef\xa9\x8e\x05\x12\x1f\x62\x28\xab\x5c\x62\x43\x06\x32\x30\xa4\xff\x1d\x1b\x18\xb5\x18\xd8\x37\xb2\xc6\xba\xc9\x99\xd4\xae\x6b\x7a\x88\xf2\x41\xbb\xfb\x90\xf4\x68\x5d\x83\x94\x18\xc2\x7b\x7d\x3f\x70\x89\xa2\x9d\x44\xfd\x3b\xbc\xbd\xa5\xf8\xe0\xbc\x50\xcd\x40\xf4\xdf\xb9\x3e\xab\xd8\xbe\xfa\xa4\xf7\x95\x93\x93\xb6\xdd\xf4\xd7\xef\xb2\x19\x15\x51\x34\xf9\x42\xe2\x4b\x00\x00\x00\xff\xff\x0d\x39\xdb\xac\x71\x02\x00\x00")

func infrastructureModulesIamIamTfBytes() ([]byte, error) {
	return bindataRead(
		_infrastructureModulesIamIamTf,
		"infrastructure/modules/iam/iam.tf",
	)
}

func infrastructureModulesIamIamTf() (*asset, error) {
	bytes, err := infrastructureModulesIamIamTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "infrastructure/modules/iam/iam.tf", size: 625, mode: os.FileMode(420), modTime: time.Unix(1455669158, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _infrastructureModulesIamOutputsTf = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xe2\xca\x2f\x2d\x29\x28\x2d\x51\x50\xca\x49\xcc\x4d\x4a\x49\x8c\x4f\x2b\xcd\x4b\x2e\xc9\xcc\xcf\x8b\xcf\x4c\x51\x52\xa8\xe6\x52\x50\x28\x4b\xcc\x29\x4d\x55\xb0\x55\x50\x52\xa9\x4e\x2c\x2f\x8e\xcf\x4c\xcc\x8d\x2f\xca\xcf\x49\xd5\x43\x53\xaf\x97\x58\x94\x57\xab\xc4\x55\x0b\x08\x00\x00\xff\xff\x97\x6c\x11\xb9\x50\x00\x00\x00")

func infrastructureModulesIamOutputsTfBytes() ([]byte, error) {
	return bindataRead(
		_infrastructureModulesIamOutputsTf,
		"infrastructure/modules/iam/outputs.tf",
	)
}

func infrastructureModulesIamOutputsTf() (*asset, error) {
	bytes, err := infrastructureModulesIamOutputsTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "infrastructure/modules/iam/outputs.tf", size: 80, mode: os.FileMode(420), modTime: time.Unix(1455669158, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _infrastructureModulesIamVariablesTf = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func infrastructureModulesIamVariablesTfBytes() ([]byte, error) {
	return bindataRead(
		_infrastructureModulesIamVariablesTf,
		"infrastructure/modules/iam/variables.tf",
	)
}

func infrastructureModulesIamVariablesTf() (*asset, error) {
	bytes, err := infrastructureModulesIamVariablesTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "infrastructure/modules/iam/variables.tf", size: 0, mode: os.FileMode(420), modTime: time.Unix(1455669158, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _infrastructureProdMainTf = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xe2\xca\xcd\x4f\x29\xcd\x49\x55\x50\xca\x4c\xcc\x55\x52\xa8\xe6\x52\x50\x28\xce\x2f\x2d\x4a\x4e\x55\xb0\x55\x50\xd2\xd3\xd3\x87\xc8\x16\xeb\x83\x64\xb9\x6a\xb9\x00\x01\x00\x00\xff\xff\x5a\x3e\xb2\x75\x2e\x00\x00\x00")

func infrastructureProdMainTfBytes() ([]byte, error) {
	return bindataRead(
		_infrastructureProdMainTf,
		"infrastructure/prod/main.tf",
	)
}

func infrastructureProdMainTf() (*asset, error) {
	bytes, err := infrastructureProdMainTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "infrastructure/prod/main.tf", size: 46, mode: os.FileMode(420), modTime: time.Unix(1455669158, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _infrastructureProdTerraformTfvars = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func infrastructureProdTerraformTfvarsBytes() ([]byte, error) {
	return bindataRead(
		_infrastructureProdTerraformTfvars,
		"infrastructure/prod/terraform.tfvars",
	)
}

func infrastructureProdTerraformTfvars() (*asset, error) {
	bytes, err := infrastructureProdTerraformTfvarsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "infrastructure/prod/terraform.tfvars", size: 0, mode: os.FileMode(420), modTime: time.Unix(1455671602, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _infrastructureStageMainTf = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xe2\xca\xcd\x4f\x29\xcd\x49\x55\x50\xca\x4c\xcc\x55\x52\xa8\xe6\x52\x50\x28\xce\x2f\x2d\x4a\x4e\x55\xb0\x55\x50\xd2\xd3\xd3\x87\xc8\x16\xeb\x83\x64\xb9\x6a\xb9\x00\x01\x00\x00\xff\xff\x5a\x3e\xb2\x75\x2e\x00\x00\x00")

func infrastructureStageMainTfBytes() ([]byte, error) {
	return bindataRead(
		_infrastructureStageMainTf,
		"infrastructure/stage/main.tf",
	)
}

func infrastructureStageMainTf() (*asset, error) {
	bytes, err := infrastructureStageMainTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "infrastructure/stage/main.tf", size: 46, mode: os.FileMode(420), modTime: time.Unix(1455669158, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _infrastructureStageTerraformTfvars = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func infrastructureStageTerraformTfvarsBytes() ([]byte, error) {
	return bindataRead(
		_infrastructureStageTerraformTfvars,
		"infrastructure/stage/terraform.tfvars",
	)
}

func infrastructureStageTerraformTfvars() (*asset, error) {
	bytes, err := infrastructureStageTerraformTfvarsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "infrastructure/stage/terraform.tfvars", size: 0, mode: os.FileMode(420), modTime: time.Unix(1455671604, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"functions/hello/index.js": functionsHelloIndexJs,
	"infrastructure/.gitignore": infrastructureGitignore,
	"infrastructure/modules/iam/iam.tf": infrastructureModulesIamIamTf,
	"infrastructure/modules/iam/outputs.tf": infrastructureModulesIamOutputsTf,
	"infrastructure/modules/iam/variables.tf": infrastructureModulesIamVariablesTf,
	"infrastructure/prod/main.tf": infrastructureProdMainTf,
	"infrastructure/prod/terraform.tfvars": infrastructureProdTerraformTfvars,
	"infrastructure/stage/main.tf": infrastructureStageMainTf,
	"infrastructure/stage/terraform.tfvars": infrastructureStageTerraformTfvars,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"functions": &bintree{nil, map[string]*bintree{
		"hello": &bintree{nil, map[string]*bintree{
			"index.js": &bintree{functionsHelloIndexJs, map[string]*bintree{}},
		}},
	}},
	"infrastructure": &bintree{nil, map[string]*bintree{
		".gitignore": &bintree{infrastructureGitignore, map[string]*bintree{}},
		"modules": &bintree{nil, map[string]*bintree{
			"iam": &bintree{nil, map[string]*bintree{
				"iam.tf": &bintree{infrastructureModulesIamIamTf, map[string]*bintree{}},
				"outputs.tf": &bintree{infrastructureModulesIamOutputsTf, map[string]*bintree{}},
				"variables.tf": &bintree{infrastructureModulesIamVariablesTf, map[string]*bintree{}},
			}},
		}},
		"prod": &bintree{nil, map[string]*bintree{
			"main.tf": &bintree{infrastructureProdMainTf, map[string]*bintree{}},
			"terraform.tfvars": &bintree{infrastructureProdTerraformTfvars, map[string]*bintree{}},
		}},
		"stage": &bintree{nil, map[string]*bintree{
			"main.tf": &bintree{infrastructureStageMainTf, map[string]*bintree{}},
			"terraform.tfvars": &bintree{infrastructureStageTerraformTfvars, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

